name: expense_tracker
description: A comprehensive expense tracking application with OCR and bank SMS integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  flutter_sms_inbox: ^1.0.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.63.0
  google_ml_kit: 0.20.0
  google_mlkit_smart_reply: 0.13.0
  flutter_native_splash: ^2.3.4
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# dependency_overrides:
#   google_mlkit_smart_reply:
#     git:
#       url: https://github.com/julleon/Google-Ml-Kit-plugin.git
#       path: packages/google_mlkit_smart_reply
